"""empty message

Revision ID: 10112081b171
Revises: 6de4db0e9976
Create Date: 2019-02-17 21:24:36.945641

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10112081b171'
down_revision = '6de4db0e9976'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'profile_pic_path',
               existing_type=sa.VARCHAR(),
               nullable='False')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'profile_pic_path',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
