"""empty message

Revision ID: 77a11cd40c76
Revises: 10112081b171
Create Date: 2019-02-17 21:29:00.853888

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77a11cd40c76'
down_revision = '10112081b171'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'pass_secure',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('users', 'profile_pic_path',
               existing_type=sa.VARCHAR(),
               nullable='False')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'profile_pic_path',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'pass_secure',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###
