"""empty message

Revision ID: 7d4024be315e
Revises: 944a46760717
Create Date: 2019-02-19 09:10:05.470506

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d4024be315e'
down_revision = '944a46760717'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'profile_pic_path',
               existing_type=sa.VARCHAR(),
               nullable='False')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'profile_pic_path',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
